VM_NAME="dev-server"

VCPUS=1
MEMORY_MB=1024

BASE_IMAGE="$HOME/lab/images/golden/debian12-base.qcow2"
VM_DISK="$HOME/lab/images/vm/dev-server.qcow2"

NETWORK="lab-net"

CLOUD_INIT_INSTANCE="$HOME/lab/vm/cloud-init/instances/dev-server"
SEED_ISO="$HOME/lab/images/seed/dev-server-seed.iso"
